# Generated by Django 3.0.8 on 2020-07-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('IP_Adress', models.CharField(max_length=60)),
                ('Model', models.CharField(max_length=60)),
                ('Version', models.CharField(max_length=60)),
                ('SerialNo', models.CharField(max_length=60)),
                ('Role', models.CharField(max_length=60)),
            ],
        ),
    ]
