# Generated by Django 3.0.8 on 2020-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='logfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='logfile',
            name='SerialNo',
        ),
        migrations.AlterField(
            model_name='logfile',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='logfile',
            name='SerialNo',
            field=models.ManyToManyField(to='adminpage.Serial', verbose_name='list of sites'),
        ),
    ]
