# Generated by Django 3.0.8 on 2020-07-27 21:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_auto_20200727_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='SerialNo',
        ),
        migrations.AddField(
            model_name='logfile',
            name='SerialNo',
            field=jsonfield.fields.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Serial',
        ),
    ]
