# Generated by Django 3.0.8 on 2020-07-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_auto_20200727_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='Role',
        ),
    ]
