# Generated by Django 2.0.13 on 2020-07-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_remove_logfile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logfile',
        ),
    ]
